### ISSUE TITLE
请教下, 用这个 把 pdf 转换为 doc的方式

### ISSUE THREAD

**Issue by ruandao** [wuguanghai45/docker-unocnv-api#1]
我用这个转换,文件打不开...

调用的命令是:

curl --form file=@test.pdf http://localhost:4000/unoconv/doc > test.doc

请教下使用方式

谢谢

**Comment by wuguanghai45** [comment]
https://github.com/zrrrzzt/tfk-api-unoconv
用的这个。。。貌似不支持pdf 转doc...

**Comment by ruandao** [comment]
谢谢
